# Generated by Django 5.0.6 on 2025-10-27 07:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='failed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sent_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='total_numbers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='api_key_used',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='media_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='message_text',
            field=models.TextField(default='Default message'),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], max_length=20),
        ),
    ]
