# Generated by Django 5.0.6 on 2025-11-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_campaign_failed_count_campaign_sent_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='template',
            field=models.TextField(blank=True, null=True),
        ),
    ]
